goroutine:
  max-goroutine: 5 #goroutine池最大线程数
  core-goroutine: 2  #goroutine池核心线程数
  timeout: 5 #goroutine池等待超时时间 单位秒

root: #默认值均为root
  account: root #root账号
  password: root #root密码
  token-enable: false #是否开启token验证
  token-expire: 36005 #token过期时间 单位秒
  token-sign: themis-root #token签名

server:
  port: 8081 #服务端口
  listen-time: 3 #状态更新时间 单位秒