/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CpuStatus: typeof import('./src/components/workspace/SystemStatusPage/CpuStatus.vue')['default']
    DiskStatus: typeof import('./src/components/workspace/SystemStatusPage/DiskStatus.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    FreshDataButton: typeof import('./src/components/workspace/SystemStatusPage/FreshDataButton.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HostStatus: typeof import('./src/components/workspace/SystemStatusPage/HostStatus.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    MemStatus: typeof import('./src/components/workspace/SystemStatusPage/MemStatus.vue')['default']
    MoonIcon: typeof import('./src/components/icon/MoonIcon.vue')['default']
    NetStatus: typeof import('./src/components/workspace/SystemStatusPage/NetStatus.vue')['default']
    PoolStatus: typeof import('./src/components/workspace/SystemStatusPage/PoolStatus.vue')['default']
    ProudIcon: typeof import('./src/components/ProudIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SunnyIcon: typeof import('./src/components/icon/SunnyIcon.vue')['default']
    ThemeButton: typeof import('./src/components/ThemeButton.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    TurtleIcon: typeof import('./src/components/TurtleIcon.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
    WifiIcon: typeof import('./src/components/WifiIcon.vue')['default']
    WorkspaceAside: typeof import('./src/components/workspace/WorkspaceAside.vue')['default']
    WorkspaceDocument: typeof import('./src/components/workspace/WorkspaceDocument.vue')['default']
    WorkspaceHead: typeof import('./src/components/workspace/WorkspaceHead.vue')['default']
    WorkspaceHome: typeof import('./src/components/workspace/WorkspaceHome.vue')['default']
    WorkspaceSystemStatus: typeof import('./src/components/workspace/WorkspaceSystemStatus.vue')['default']
  }
}
